## **_N U M P Y - Numerical Python_**
    .Mostly usedin the context of representing Vectors and Matrices
    .Similar to mathematics and mathematical operations
    .represents lists and matrices in the form of arrays/lists known as numpy lists

In [53]:
import numpy as np

In [9]:
#Numpy Array Initialzation
x= np.array([1,2,3])
y= np.array([4,5,6])

In [10]:
z=x+y
print(z)

[5 7 9]


In [12]:
#Array Multiplication
z=x*y
print(z)

[ 4 10 18]


In [22]:
#Array Scaling - scaling a vector using a magniitude value x
'''During Numpy scaling, a process called numpy-broadcasting happens that will help scale the vectors in their resultant form
'''
print(f"{z*3}")
print(z*3)

[12 30 54]
[12 30 54]


In [23]:
#Squaring
print(z**2)

[ 16 100 324]


In [24]:
np.log10(z)

array([0.60205999, 1.        , 1.25527251])

In [25]:
print(z)

[ 4 10 18]


In [26]:
print(np.log(z))

[1.38629436 2.30258509 2.89037176]


In [30]:
a=np.array([1,2,3,4,5])
c=5 #some constant
print(a+c)
#c-->>[5,5,5,5,5] -> this is called as numpy broadcasting


[ 6  7  8  9 10]


In [37]:
#mathematical constants in numpy
np.e, np.pi, np.False_

(2.718281828459045, 3.141592653589793, False)

In [36]:
'''Note : Python's way of representing numericals with commas'''
1_000, 100_000, 1_00_000

(1000, 100000, 100000)

In [42]:
#Dot Product
a=np.array([1,2,3,4,5,6])
b=np.array([3,4,5,6,7,8])
np.dot(a,b)

133

In [47]:
#Zeros and Ones Vectors
print(np.zeros(6))
print(np.ones(8))

[0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1.]


In [48]:
np.arange?

Docstring:
arange([start,] stop[, step,], dtype=None, *, like=None)

Return evenly spaced values within a given interval.

``arange`` can be called with a varying number of positional arguments:

* ``arange(stop)``: Values are generated within the half-open interval
  ``[0, stop)`` (in other words, the interval including `start` but
  excluding `stop`).
* ``arange(start, stop)``: Values are generated within the half-open
  interval ``[start, stop)``.
* ``arange(start, stop, step)`` Values are generated within the half-open
  interval ``[start, stop)``, with spacing between values given by
  ``step``.

For integer arguments the function is roughly equivalent to the Python
built-in :py:class:`range`, but returns an ndarray rather than a ``range``
instance.

When using a non-integer step, such as 0.1, it is often better to use
`numpy.linspace`.

See the Warning sections below for more information.

Parameters
----------
start : integer or real, optional
    Start of interval.  The interva

In [50]:
np.arange(1,6)

array([1, 2, 3, 4, 5])

In [51]:
list(range(1,6))

[1, 2, 3, 4, 5]

In [52]:
np.arange(0,7,0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5])

## Norm of a vector

For a vector $\mathbf{x}$:

$$
\mathbf{x} = \begin{bmatrix}
1\\
2\\
3
\end{bmatrix}
$$

The $L_2$ norm is defind as:

$$
||\mathbf{x}||_2 = \sqrt{1^2 + 2^2 + 3^2} = \sqrt{14}
$$

The $L_1$ norm is defind as:

$$
||\mathbf{x}||_1 = |1| + |2| + |3| = 6
$$

In `NumPy`:

In [56]:
#L2 Norm
x=np.array([1,2,3,4,5])
nrm=np.linalg.norm(x)
print(nrm)

7.416198487095663


In [59]:
# L1-norm
x = np.array([1, 2, 3])
norm = np.linalg.norm(x, ord = 1)
norm 

#We can get L1 norm by also changing the ord to 2

6.0

## Shape, Size, Dimension of a Vector

- **Shape**: This refers to the $ n \times n $ representation of a vector if it is considered in \( n \)-dimensional space.

- **Dimension (ndim)**: This indicates the dimensional space the vector exists in.
    > In linear algebra, the dimension of a vector with 4 elements is represented as $\mathbb{R}^{4}$.  
    > However, in NumPy, we can represent it in a single line as a one-dimensional array.

- **Size**: This represents the total number of elements present in the vector/the numpy array.


In [61]:
#Dimension
test=np.array([1,2,3,4,5,6])
test_2=np.array([[1,2,3,4,5],[5,6,7,8,9]])
print(test.ndim, test_2.ndim)

1 2


In [62]:
#Shape
print(test.shape, test_2.shape)

(6,) (2, 5)


In [64]:
#Size
print(test.size, test_2.size)

6 10


## 